"use client";
import { useEffect,useMemo,useRef,useState } from "react";
import { X,RotateCcw,Maximize2,Sparkles,Users,Info } from "lucide-react";
type Person={id:string;user_id?:string|null;display_name:string;gender?:string|null;birth_year?:number|null;birth_date?:string|null;relation?:string;via_id?:string;via_parent_id?:string;via_child_id?:string};
type Tree={centre:Person;parents?:Person[];spouses?:Person[];children?:Person[];siblings?:Person[];levels_up?:Person[][];levels_down?:Person[][];spouses_of?:Record<string,Person[]>;siblings_of?:Record<string,Person[]>};
const C={self:0xf5b942,parent:0x8b5cf6,gp:0x3b82f6,ancestor:0x14b8a6,child:0x10b981,gc:0xf97316,spouse:0xec4899,sibling:0xfacc15};
const age=(p:Person)=>{const y=p.birth_year||(p.birth_date?+p.birth_date.slice(0,4):0);return y>1800?Math.max(0,new Date().getFullYear()-y):null};
const sex=(p:Person)=>{const g=String(p.gender||"").toLowerCase();return g==="female"||g==="f"?"female":g==="male"||g==="m"?"male":"neutral"};
const gen=(p:Person,cid:string)=>{const r=String(p.relation||"").toLowerCase();if(p.id===cid||r==="self")return 0;if(["father","mother","parent"].includes(r))return 1;if(["grandfather","grandmother"].includes(r))return 2;if(["child","son","daughter"].includes(r))return-1;if(r==="grandchild")return-2;return 0};
const color=(p:Person,cid:string)=>{const r=String(p.relation||"").toLowerCase(),g=gen(p,cid);if(r==="spouse")return C.spouse;if(["sibling","brother","sister"].includes(r))return C.sibling;if(g===0)return C.self;if(g===1)return C.parent;if(g===2)return C.gp;if(g>2)return C.ancestor;if(g===-1)return C.child;return C.gc};

export default function Vanshawali3D({rootId,onClose}:{rootId:string;onClose:()=>void}){
 const host=useRef<HTMLDivElement>(null),runtime=useRef<any>(null);
 const [tree,setTree]=useState<Tree|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[selected,setSelected]=useState<Person|null>(null),[year,setYear]=useState(2026);
 const people=useMemo(()=>{if(!tree)return[];const a:Person[]=[];const add=(p?:Person)=>{if(p&&!a.some(x=>x.id===p.id))a.push(p)};add(tree.centre);[...(tree.parents||[]),...(tree.spouses||[]),...(tree.children||[]),...(tree.siblings||[])].forEach(add);(tree.levels_up||[]).flat().forEach(add);(tree.levels_down||[]).flat().forEach(add);Object.values(tree.spouses_of||{}).flat().forEach(add);Object.values(tree.siblings_of||{}).flat().forEach(add);return a},[tree]);
 useEffect(()=>{let ok=true;setLoading(true);fetch("/api/vanshawali?userId="+encodeURIComponent(rootId),{cache:"no-store"}).then(r=>r.json()).then(d=>{if(!ok)return;if(!d.tree)throw Error(d.error||"Family tree unavailable");setTree(d.tree)}).catch(e=>ok&&setError(e.message||"Could not load family tree")).finally(()=>ok&&setLoading(false));return()=>{ok=false}},[rootId]);
 useEffect(()=>{if(!host.current||!tree)return;let dead=false,clean=()=>{};(async()=>{try{
 // @ts-ignore
 const THREE:any=await import(/* webpackIgnore: true */"https://esm.sh/three@0.180.0");
 // @ts-ignore
 const {GLTFLoader}:any=await import(/* webpackIgnore: true */"https://esm.sh/three@0.180.0/examples/jsm/loaders/GLTFLoader.js?deps=three@0.180.0");
 if(dead||!host.current)return;const el=host.current,scene=new THREE.Scene();scene.background=new THREE.Color(0x07111f);scene.fog=new THREE.FogExp2(0x07111f,.018);
 const cam=new THREE.PerspectiveCamera(42,el.clientWidth/Math.max(1,el.clientHeight),.1,500);cam.position.set(0,7,24);
 const ren=new THREE.WebGLRenderer({antialias:true,powerPreference:"high-performance"});ren.setPixelRatio(Math.min(devicePixelRatio||1,1.75));ren.setSize(el.clientWidth,el.clientHeight,false);ren.outputColorSpace=THREE.SRGBColorSpace;ren.shadowMap.enabled=true;el.appendChild(ren.domElement);
 scene.add(new THREE.HemisphereLight(0xcfe3ff,0x111827,2));const dl=new THREE.DirectionalLight(0xffe3ad,3);dl.position.set(-10,18,12);dl.castShadow=true;scene.add(dl);const pl=new THREE.PointLight(0x55dfff,1.8,80);pl.position.set(12,7,-8);scene.add(pl);
 const floor=new THREE.Mesh(new THREE.CircleGeometry(48,96),new THREE.MeshStandardMaterial({color:0x0c1a2a,roughness:.92,metalness:.04}));floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;scene.add(floor);
 const ring=new THREE.Mesh(new THREE.RingGeometry(11.5,11.58,96),new THREE.MeshBasicMaterial({color:0x2b536f,transparent:true,opacity:.35,side:THREE.DoubleSide}));ring.rotation.x=-Math.PI/2;scene.add(ring);
 const loader=new GLTFLoader();const [male,female]=await Promise.all([new Promise<any>((a,b)=>loader.load("https://readyplayerme.github.io/visage/male.glb",a,undefined,b)),new Promise<any>((a,b)=>loader.load("https://readyplayerme.github.io/visage/female.glb",a,undefined,b))]);if(dead)return;
 const pos=new Map<string,any>(),groups=new Map<number,Person[]>();people.forEach(p=>{const g=gen(p,tree.centre.id);if(!groups.has(g))groups.set(g,[]);groups.get(g)!.push(p)});
 [...groups.keys()].sort((a,b)=>b-a).forEach(g=>{const list=groups.get(g)!;const spacing=Math.max(2.7,18/Math.max(2,list.length)),mid=(list.length-1)/2;list.forEach((p,i)=>pos.set(p.id,{x:(i-mid)*spacing,y:g*4.5+2.1,z:Math.sin(i*1.37+g)*1.4}))});
 const objs=new Map<string,any>(),hit:any[]=[];
 people.forEach(p=>{const o=new THREE.Group(),q=pos.get(p.id);o.position.set(q.x,q.y,q.z);o.userData.person=p;const col=color(p,tree.centre.id);const base=new THREE.Mesh(new THREE.CylinderGeometry(.75,.92,.18,40),new THREE.MeshStandardMaterial({color:col,emissive:col,emissiveIntensity:.2,metalness:.25,roughness:.45}));base.position.y=.05;o.add(base);
 const av=(sex(p)==="female"?female.scene:male.scene).clone(true),a=age(p),s=a==null?.92:a<5?.42:a<13?.58:a<20?.74:a>70?.88:.96;av.scale.setScalar(s);av.rotation.y=Math.PI;av.traverse((m:any)=>{if(m.isMesh){m.castShadow=true;m.receiveShadow=true}});o.add(av);scene.add(o);objs.set(p.id,o);hit.push(o)});
 const lm=(c:number)=>new THREE.LineBasicMaterial({color:c,transparent:true,opacity:.9}),seen=new Set<string>(),edge=(a:string,b:string,c:number)=>{if(!a||!b||a===b||!pos.has(a)||!pos.has(b))return;const k=[a,b].sort().join("|")+c;if(seen.has(k))return;seen.add(k);const A=pos.get(a),B=pos.get(b),pts=[new THREE.Vector3(A.x,A.y+.3,A.z),new THREE.Vector3((A.x+B.x)/2,(A.y+B.y)/2+.7,(A.z+B.z)/2),new THREE.Vector3(B.x,B.y+.3,B.z)];scene.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(pts),lm(c)))};
 people.forEach(p=>{const v=p.via_id||p.via_parent_id||p.via_child_id;if(v)edge(v,p.id,String(p.relation||"")==="spouse"?C.spouse:["sibling","brother","sister"].includes(String(p.relation||""))?C.sibling:C.self)});(tree.parents||[]).forEach(p=>edge(p.id,tree.centre.id,C.parent));(tree.children||[]).forEach(p=>edge(tree.centre.id,p.id,C.child));(tree.spouses||[]).forEach(p=>edge(tree.centre.id,p.id,C.spouse));(tree.siblings||[]).forEach(p=>edge(tree.centre.id,p.id,C.sibling));
 const ray=new THREE.Raycaster(),mouse=new THREE.Vector2();let drag=false,lx=0,ly=0,yaw=0,pitch=-.15,distance=24,target=new THREE.Vector3(0,3,0);const update=()=>{const cp=Math.cos(pitch);cam.position.set(target.x+distance*Math.sin(yaw)*cp,target.y+distance*Math.sin(-pitch),target.z+distance*Math.cos(yaw)*cp);cam.lookAt(target)};
 const down=(e:PointerEvent)=>{drag=false;lx=e.clientX;ly=e.clientY;ren.domElement.setPointerCapture(e.pointerId)},move=(e:PointerEvent)=>{if(!(e.buttons&1))return;const dx=e.clientX-lx,dy=e.clientY-ly;if(Math.abs(dx)+Math.abs(dy)>3)drag=true;yaw-=dx*.005;pitch=Math.max(-1.1,Math.min(.65,pitch+dy*.004));lx=e.clientX;ly=e.clientY;update()},up=(e:PointerEvent)=>{try{ren.domElement.releasePointerCapture(e.pointerId)}catch{}},wheel=(e:WheelEvent)=>{e.preventDefault();distance=Math.max(8,Math.min(50,distance+e.deltaY*.018));update()},click=(e:PointerEvent)=>{if(drag)return;const r=ren.domElement.getBoundingClientRect();mouse.x=(e.clientX-r.left)/r.width*2-1;mouse.y=-((e.clientY-r.top)/r.height)*2+1;ray.setFromCamera(mouse,cam);let o:any=ray.intersectObjects(hit,true)[0]?.object;while(o&&!o.userData?.person)o=o.parent;if(o?.userData?.person)setSelected(o.userData.person)};
 ren.domElement.addEventListener("pointerdown",down);ren.domElement.addEventListener("pointermove",move);ren.domElement.addEventListener("pointerup",up);ren.domElement.addEventListener("click",click);ren.domElement.addEventListener("wheel",wheel,{passive:false});
 const resize=()=>{const w=el.clientWidth,h=el.clientHeight;cam.aspect=w/Math.max(1,h);cam.updateProjectionMatrix();ren.setSize(w,h,false)};window.addEventListener("resize",resize);const clock=new THREE.Clock();let raf=0;const loop=()=>{const t=clock.getElapsedTime();objs.forEach((o:any)=>o.rotation.y=Math.sin(t*.22+o.position.x)*.025);ring.rotation.z=t*.03;ren.render(scene,cam);raf=requestAnimationFrame(loop)};loop();runtime.current={home:()=>{target.set(0,3,0);distance=24;yaw=0;pitch=-.15;update()}};clean=()=>{cancelAnimationFrame(raf);window.removeEventListener("resize",resize);ren.domElement.removeEventListener("pointerdown",down);ren.domElement.removeEventListener("pointermove",move);ren.domElement.removeEventListener("pointerup",up);ren.domElement.removeEventListener("click",click);ren.domElement.removeEventListener("wheel",wheel);ren.dispose();if(ren.domElement.parentNode===el)el.removeChild(ren.domElement)};update();
 }catch(e:any){if(!dead)setError(e?.message||"3D renderer failed")}})();return()=>{dead=true;clean()}},[tree,people]);
 return <div className="fixed inset-0 z-[100] bg-[#07111f] text-white overflow-hidden">
 <div className="absolute inset-x-0 top-0 z-30 flex justify-between items-center p-3 bg-gradient-to-b from-[#07111f] to-transparent pointer-events-none"><div><p className="text-[10px] uppercase tracking-[.22em] text-cyan-200/70">Digital Family Universe</p><h2 className="text-lg font-bold">3D Vansh Vruksh</h2><p className="text-[10px] text-slate-300">Living lineage · generations · relationships</p></div><button onClick={onClose} className="pointer-events-auto w-10 h-10 rounded-full bg-white/10 border border-white/15 flex items-center justify-center"><X size={18}/></button></div>
 <div ref={host} className="absolute inset-0"/>
 <div className="absolute left-3 top-24 z-20 rounded-2xl border border-white/10 bg-black/25 backdrop-blur-md p-3 text-[10px] text-slate-200"><div className="flex items-center gap-2 font-semibold mb-2"><Sparkles size={13} className="text-amber-300"/>Relationship key</div>{Object.entries({Self:C.self,Parents:C.parent,Grandparents:C.gp,Ancestors:C.ancestor,Children:C.child,Spouse:C.spouse,Siblings:C.sibling}).map(([k,c])=><div key={k} className="flex items-center gap-2 py-0.5"><span className="w-2.5 h-2.5 rounded-full" style={{background:"#"+(c as number).toString(16).padStart(6,"0")}}/>{k}</div>)}</div>
 <div className="absolute right-3 bottom-4 z-20 flex gap-2"><button onClick={()=>runtime.current?.home?.()} className="px-3 py-2 rounded-xl bg-white/10 border border-white/10 text-xs flex items-center gap-1.5"><RotateCcw size={13}/> Reset</button><button onClick={()=>host.current?.requestFullscreen?.()} className="px-3 py-2 rounded-xl bg-white/10 border border-white/10 text-xs flex items-center gap-1.5"><Maximize2 size={13}/> Fullscreen</button></div>
 <div className="absolute left-3 bottom-4 z-20 flex gap-2 text-[10px] text-slate-300"><span className="px-2.5 py-1.5 rounded-xl bg-white/10 border border-white/10 flex items-center gap-1.5"><Users size={12}/> {people.length} people</span><label className="px-2.5 py-1.5 rounded-xl bg-white/10 border border-white/10">Timeline {year}<input type="range" min="1900" max="2026" value={year} onChange={e=>setYear(+e.target.value)} className="ml-2 w-20 accent-amber-400"/></label></div>
 {loading&&<div className="absolute inset-0 z-40 flex items-center justify-center bg-[#07111f]/85"><div className="text-center"><p className="text-sm font-semibold text-amber-300">Building your family universe…</p><p className="text-[10px] text-slate-400 mt-1">Loading 3D people and relationships</p></div></div>}
 {error&&!loading&&<div className="absolute inset-0 z-40 flex items-center justify-center bg-[#07111f]/90"><div className="text-center max-w-sm px-6"><p className="text-sm font-semibold text-red-300">3D view could not start</p><p className="text-xs text-slate-400 mt-2">{error}</p><button onClick={onClose} className="mt-4 px-4 py-2 rounded-xl bg-amber-400 text-black text-xs font-bold">Back to Vanshavali</button></div></div>}
 {selected&&<div className="absolute right-3 top-24 z-40 w-60 rounded-2xl border border-white/10 bg-[#07111f]/85 backdrop-blur-xl p-4 shadow-2xl"><div className="flex justify-between gap-2"><div><p className="text-sm font-bold">{selected.display_name}</p><p className="text-[10px] text-slate-400">{selected.relation||"Family member"}{age(selected)!=null?" · age "+age(selected):""}</p></div><button onClick={()=>setSelected(null)}><X size={14}/></button></div><div className="mt-3 text-[10px] text-slate-300 space-y-1"><p>Generation: {gen(selected,tree?.centre.id||"")===0?"Your generation":gen(selected,tree?.centre.id||"")>0?gen(selected,tree?.centre.id||"")+" level(s) above":Math.abs(gen(selected,tree?.centre.id||""))+" level(s) below"}</p>{selected.birth_year&&<p>Born: {selected.birth_year}</p>}</div><div className="mt-3 rounded-xl bg-white/5 p-2 text-[9px] text-slate-400 flex gap-2"><Info size={12} className="text-cyan-300 shrink-0"/>Drag to orbit · wheel/pinch to zoom · tap a person for details.</div></div>}
 </div>
}
